export default {
  red: 'Đỏ',
  orange: 'Cam',
  yellow: 'Vàng',
  green: 'Xanh lá',
  blue: 'Xanh dương',
  purple: 'Tím',
  pink: 'Hồng',
  brown: 'Nâu',
  black: 'Đen',
  white: 'Trắng',
  gray: 'Xám',
  silver: 'Bạc',
  gold: 'Vàng kim',
  navy: 'Xanh đậm',
  teal: 'Xanh lam',
  maroon: 'Đỏ thẫm',
  coral: 'San hô',
  lavender: 'Oải hương',
  beige: 'Be',
  olive: 'Olive',
  indigo: 'Chàm',
  cyan: 'Xanh cyan',
  magenta: 'Đỏ tím',
  lime: 'Xanh chanh',
  khaki: 'Kaki',
  mustard: 'Vàng mù tạt',
  turquoise: 'Xanh lục',
  peach: 'Hồng đào',
  mint: 'Xanh bạc hà',
  plum: 'Mận',
  ivory: 'Ngà',
  charcoal: 'Than',
  chocolate: 'Sô cô la',
  salmon: 'Hồng cá hồi',
  wheat: 'Lúa mì',
  raspberry: 'Mâm xôi',
  orchid: 'Hoa lan',
  amber: 'Hổ phách',
  violet: 'Tía',
  aquamarine: 'Xanh nước biển',
  jade: 'Ngọc bích',
  ruby: 'Hồng ngọc',
  sapphire: 'Lam ngọc',
  emerald: 'Lục bảo',
  bronze: 'Đồng',
  copper: 'Đồng đỏ',
  obsidian: 'Đá vỏ chai',
  pearl: 'Ngọc trai',
  rose: 'Hồng phấn',
  sienna: 'Nâu đất',
  tan: 'Nâu nhạt',
  taupe: 'Nâu xám',
  sand: 'Cát',
  sepia: 'Nâu đỏ',
  cobalt: 'Xanh coban',
  moss: 'Xanh rêu',
  slate: 'Xám đá phiến',
  rust: 'Gỉ sét',
}
